package vista;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Auto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author PC
 */
public class FrmAutos extends javax.swing.JFrame {

    public static ArrayList<Auto> listaDeAutos;
    public static ArrayList<Auto> listaDeAutosSeleccionados;
    Auto a;

    DefaultTableModel dtmAutos;

    /**
     * Creates new form FrmAutos
     */
    public FrmAutos() {
        initComponents();
        dtmAutos = new DefaultTableModel();
        dtmAutos.addColumn("Marca");
        dtmAutos.addColumn("Color");
        dtmAutos.addColumn("Tipo");
        dtmAutos.addColumn("Precio");
        tblAutos.setModel(dtmAutos);
        desactivarComponentes();
        listaDeAutos = new ArrayList<>();
        listaDeAutosSeleccionados = new ArrayList<>();
        inicializarStock();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutos = new javax.swing.JTable();
        cmbStock = new javax.swing.JComboBox<>();
        lblStock = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblIngresarNuevoAuto = new javax.swing.JLabel();
        lblMarcaAutoNuevo = new javax.swing.JLabel();
        txtMarcaAutoNuevo = new javax.swing.JTextField();
        lblColorAutoNuevo = new javax.swing.JLabel();
        txtColorAutoNuevo = new javax.swing.JTextField();
        lblTipoAutoNuevo = new javax.swing.JLabel();
        txtTipoAutoNuevo = new javax.swing.JTextField();
        lblPrecioAutoNuevo = new javax.swing.JLabel();
        txtPrecioAutoNuevo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnConfirmarSeleccion = new javax.swing.JButton();
        btnAgregarALaCompra = new javax.swing.JButton();
        btnLimpiarAutosNuevos = new javax.swing.JButton();
        btnLimpiarStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario de autos");

        tblAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAutos);

        cmbStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Color", "Marca", "Tipo" }));
        cmbStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStockActionPerformed(evt);
            }
        });

        lblStock.setText("Stock");

        lblMarca.setText("Marca");

        lblColor.setText("Color");

        lblTipo.setText("Tipo");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblIngresarNuevoAuto.setText("Ingresar nuevo auto");

        lblMarcaAutoNuevo.setText("Marca");

        lblColorAutoNuevo.setText("Color");

        lblTipoAutoNuevo.setText("Tipo");

        lblPrecioAutoNuevo.setText("Precio");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnConfirmarSeleccion.setText("Confirmar Seleccion");
        btnConfirmarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarSeleccionActionPerformed(evt);
            }
        });

        btnAgregarALaCompra.setText("Agregar a la compra");
        btnAgregarALaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarALaCompraActionPerformed(evt);
            }
        });

        btnLimpiarAutosNuevos.setText("Limpiar");
        btnLimpiarAutosNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAutosNuevosActionPerformed(evt);
            }
        });

        btnLimpiarStock.setText("limpiar");
        btnLimpiarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarca)
                            .addComponent(lblColor)
                            .addComponent(lblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbStock, 0, 166, Short.MAX_VALUE)
                                .addComponent(txtMarca)
                                .addComponent(txtColor)
                                .addComponent(txtTipo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarStock)))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMarcaAutoNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(txtMarcaAutoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                            .addComponent(lblIngresarNuevoAuto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblColorAutoNuevo)
                                    .addComponent(lblTipoAutoNuevo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtColorAutoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(txtTipoAutoNuevo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPrecioAutoNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecioAutoNuevo))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnConfirmarSeleccion)
                        .addGap(82, 82, 82)
                        .addComponent(btnAgregarALaCompra))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnGuardar)
                        .addGap(48, 48, 48)
                        .addComponent(btnLimpiarAutosNuevos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStock)
                    .addComponent(lblIngresarNuevoAuto))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColor)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiarStock)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarcaAutoNuevo)
                            .addComponent(txtMarcaAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColorAutoNuevo)
                            .addComponent(txtColorAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoAutoNuevo)
                            .addComponent(txtTipoAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecioAutoNuevo)
                            .addComponent(txtPrecioAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiarAutosNuevos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarSeleccion)
                    .addComponent(btnAgregarALaCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStockActionPerformed
        String stockSeleccionado = cmbStock.getSelectedItem().toString();
        switch (stockSeleccionado) {
            case "Color":
                activarComponentesParaColor();
                break;
            case "Marca":
                activarComponentesParaMarca();
                break;
            case "Tipo":
                activarComponentesParaTipo();
                break;

        }

    }//GEN-LAST:event_cmbStockActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        limpiarTablaDeAutos();
        boolean encontrado = false;
        for (Auto a : listaDeAutos) {
            if (a.getColor().toLowerCase().equals(txtColor.getText().toLowerCase())) {
                agregarAutoALaTabla(a);
                encontrado = true;
            } else if (a.getMarca().toLowerCase().equals(txtMarca.getText().toLowerCase())) {
                agregarAutoALaTabla(a);
                encontrado = true;
            } else if (a.getTipo().toLowerCase().equals(txtTipo.getText().toLowerCase())) {
                agregarAutoALaTabla(a);
                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(rootPane, "Auto no disponible");
        }


    }//GEN-LAST:event_btnBuscarActionPerformed
    private void limpiarTablaDeAutos() {
        for (int i = 0; i < tblAutos.getRowCount(); i++) {
            dtmAutos.removeRow(i);
            i -= 1;

        }

    }

    private void desactivarComponentes() {
        lblColor.setVisible(false);
        lblMarca.setVisible(false);
        lblTipo.setVisible(false);
        txtColor.setEnabled(false);
        txtColor.setVisible(false);
        txtMarca.setEnabled(false);
        txtMarca.setVisible(false);
        txtTipo.setEnabled(false);
        txtTipo.setVisible(false);
        btnBuscar.setVisible(false);
        btnLimpiarStock.setVisible(false);

    }

    private void activarComponentesParaColor() {
        lblColor.setVisible(true);
        lblMarca.setVisible(false);
        lblTipo.setVisible(false);
        txtColor.setEnabled(true);
        txtColor.setVisible(true);
        txtMarca.setEnabled(false);
        txtMarca.setVisible(false);
        txtTipo.setEnabled(false);
        txtTipo.setVisible(false);
        btnBuscar.setVisible(true);
        btnLimpiarStock.setVisible(true);

    }

    private void activarComponentesParaMarca() {
        lblColor.setVisible(false);
        lblMarca.setVisible(true);
        lblTipo.setVisible(false);
        txtColor.setEnabled(false);
        txtColor.setVisible(false);
        txtMarca.setEnabled(true);
        txtMarca.setVisible(true);
        txtTipo.setEnabled(false);
        txtTipo.setVisible(false);
        btnBuscar.setVisible(true);
        btnLimpiarStock.setVisible(true);

    }

    private void activarComponentesParaTipo() {
        lblColor.setVisible(false);
        lblMarca.setVisible(false);
        lblTipo.setVisible(true);
        txtColor.setEnabled(false);
        txtColor.setVisible(false);
        txtMarca.setEnabled(false);
        txtMarca.setVisible(false);
        txtTipo.setEnabled(true);
        txtTipo.setVisible(true);
        btnBuscar.setVisible(true);
        btnLimpiarStock.setVisible(true);

    }

    private void inicializarStock() {
        listaDeAutos.add(new Auto("Toyota", "Rojo", "Sedan", 25000.00));
        listaDeAutos.add(new Auto("Honda", "Azul", "SUV", 30000.00));
        listaDeAutos.add(new Auto("Chevrolet", "Negro", "Pickup", 35000.00));
        listaDeAutos.add(new Auto("Ford", "Blanco", "Convertible", 45000.00));
        listaDeAutos.add(new Auto("Nissan", "Verde", "Hatchback", 20000.00));
        listaDeAutos.add(new Auto("BMW", "Gris", "Coupe", 55000.00));
        listaDeAutos.add(new Auto("Mercedes", "Rojo", "Sedan", 60000.00));
        listaDeAutos.add(new Auto("Audi", "Negro", "SUV", 65000.00));
        listaDeAutos.add(new Auto("Kia", "Blanco", "Hatchback", 18000.00));
        listaDeAutos.add(new Auto("Volkswagen", "Amarillo", "Sedan", 22000.00));

    }

    private void agregarAutoALaTabla(Auto a) {
        dtmAutos.addRow(new Object[]{a.getMarca(), a.getColor(), a.getTipo(), a.getPrecio()});
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            listaDeAutos.add(new Auto(txtMarcaAutoNuevo.getText(), txtColorAutoNuevo.getText(), txtTipoAutoNuevo.getText(), Double.parseDouble(txtPrecioAutoNuevo.getText())));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Por favor llene todo lo solicitado");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConfirmarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarSeleccionActionPerformed
        // TODO add your handling code here:
        FrmConfirmacionDeCompra pa = new FrmConfirmacionDeCompra();
        pa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConfirmarSeleccionActionPerformed
    private void guardarAutoSeleccionado() {
        int[] filasSeleccionadas = tblAutos.getSelectedRows();
        // Iterar sobre las filas seleccionadas
        for (int fila : filasSeleccionadas) {
            // Obtener el modelo de la tabla y la fila correspondiente a la selección
            dtmAutos = (DefaultTableModel) tblAutos.getModel();
            Object[] filaSeleccionada = new Object[dtmAutos.getColumnCount()];

            for (int i = 0; i < dtmAutos.getColumnCount(); i++) {
                filaSeleccionada[i] = dtmAutos.getValueAt(fila, i);
            }

            // Crear un objeto Auto a partir de la fila seleccionada y añadirlo al ArrayList
            Auto autoSeleccionado = new Auto(filaSeleccionada[0].toString(), filaSeleccionada[1].toString(), filaSeleccionada[2].toString(), Double.parseDouble(filaSeleccionada[3].toString()));
            listaDeAutosSeleccionados.add(autoSeleccionado);
        }

    }


    private void btnAgregarALaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarALaCompraActionPerformed
        guardarAutoSeleccionado();


    }//GEN-LAST:event_btnAgregarALaCompraActionPerformed
    private void limpiar() {
        txtColorAutoNuevo.setText("");
        txtMarcaAutoNuevo.setText("");
        txtPrecioAutoNuevo.setText("");
        txtTipoAutoNuevo.setText("");

    }
    private void btnLimpiarAutosNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAutosNuevosActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarAutosNuevosActionPerformed

    private void btnLimpiarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarStockActionPerformed
        txtColor.setText("");
        txtMarca.setText("");
        txtTipo.setText("");
    }//GEN-LAST:event_btnLimpiarStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarALaCompra;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConfirmarSeleccion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiarAutosNuevos;
    private javax.swing.JButton btnLimpiarStock;
    private javax.swing.JComboBox<String> cmbStock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColorAutoNuevo;
    private javax.swing.JLabel lblIngresarNuevoAuto;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarcaAutoNuevo;
    private javax.swing.JLabel lblPrecioAutoNuevo;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoAutoNuevo;
    private javax.swing.JTable tblAutos;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtColorAutoNuevo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMarcaAutoNuevo;
    private javax.swing.JTextField txtPrecioAutoNuevo;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTipoAutoNuevo;
    // End of variables declaration//GEN-END:variables
}
