/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Validador.Validador;

/**
 *
 * @author stalin
 */
public class RegistroCliente extends javax.swing.JFrame {

    public RegistroCliente() {
        initComponents();
        lblErrorApellido.setVisible(false);
        lblErrorCedula.setVisible(false);
        lblErrorDireccion.setVisible(false);
        lblErrorNombre.setVisible(false);
        lblErrorTelefono.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTelefonoCliente = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblApellidoCliente = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        lblDireccionCliente = new javax.swing.JLabel();
        txtApellidoCliente = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();
        lblErrorTelefono = new javax.swing.JLabel();
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorApellido = new javax.swing.JLabel();
        lblErrorCedula = new javax.swing.JLabel();
        lblErrorDireccion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cliente.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, 190));

        lblTelefonoCliente.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        lblTelefonoCliente.setText("Telefono: ");
        jPanel2.add(lblTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 100, 30));

        lblNombreCliente.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        lblNombreCliente.setText("Nombres: ");
        jPanel2.add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 30));

        lblApellidoCliente.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        lblApellidoCliente.setText("Apellidos: ");
        jPanel2.add(lblApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 30));

        lblIdCliente.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        lblIdCliente.setText("Cedula ID: ");
        jPanel2.add(lblIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, 30));

        lblDireccionCliente.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        lblDireccionCliente.setText("Direccion: ");
        jPanel2.add(lblDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, 30));

        txtApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoClienteActionPerformed(evt);
            }
        });
        txtApellidoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoClienteKeyReleased(evt);
            }
        });
        jPanel2.add(txtApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 210, 30));

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });
        txtIdCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdClienteKeyReleased(evt);
            }
        });
        jPanel2.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 210, 30));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 210, 30));

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        txtNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyReleased(evt);
            }
        });
        jPanel2.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 210, 30));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 210, 30));

        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarClienteMouseClicked(evt);
            }
        });
        jPanel2.add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 140, 40));

        lblErrorTelefono.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorTelefono.setText("ERROR");
        jPanel2.add(lblErrorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 50, 20));

        lblErrorNombre.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorNombre.setText("ERROR");
        jPanel2.add(lblErrorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 50, 20));

        lblErrorApellido.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorApellido.setText("ERROR");
        jPanel2.add(lblErrorApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 50, 20));

        lblErrorCedula.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorCedula.setText("ERROR");
        jPanel2.add(lblErrorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 50, 20));

        lblErrorDireccion.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorDireccion.setText("ERROR");
        jPanel2.add(lblErrorDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 50, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 470, 580));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo3 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 470, 520));

        jLabel8.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel8.setText("REGISTRO CLIENTE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
        if (Validador.esNombreCorrecto(txtNombreCliente.getText())) {
            lblErrorNombre.setVisible(false);
        } else {
            lblErrorNombre.setText("El nombre no es valido");
            lblErrorNombre.setVisible(true);
        }
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtNombreClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyReleased
        // TODO add your handling code here:
        if (Validador.esNombreCorrecto(txtNombreCliente.getText())) {
            lblErrorNombre.setVisible(false);
        } else {
            lblErrorNombre.setText("El nombre no es valido");
            lblErrorNombre.setVisible(true);
        }

    }//GEN-LAST:event_txtNombreClienteKeyReleased

    private void txtApellidoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoClienteKeyReleased
        // TODO add your handling code here:
        if (Validador.esApellidoCorrecto(txtApellidoCliente.getText())) {
            lblErrorApellido.setVisible(false);
        } else {
            lblErrorApellido.setText("Usuario incorrecto");
            lblErrorApellido.setVisible(true);
        }

    }//GEN-LAST:event_txtApellidoClienteKeyReleased

    private void btnRegistrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarClienteMouseClicked
        // TODO add your handling code here:

        FrmAutos a = new FrmAutos();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistrarClienteMouseClicked

    private void txtApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoClienteActionPerformed
        // TODO add your handling code here:
        if (Validador.esApellidoCorrecto(txtApellidoCliente.getText())) {
            lblErrorApellido.setVisible(false);
        } else {
            lblErrorApellido.setText("El apellido no es valido");
            lblErrorApellido.setVisible(true);
        }
    }//GEN-LAST:event_txtApellidoClienteActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
        if (Validador.esCedulaCorrecta(txtIdCliente.getText())) {
            lblErrorCedula.setVisible(false);
        } else {
            lblErrorCedula.setText("El número de cédula no es valido");
            lblErrorCedula.setVisible(true);
        }
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtIdClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdClienteKeyReleased
        // TODO add your handling code here:
        if (Validador.esCedulaCorrecta(txtIdCliente.getText())) {
            lblErrorCedula.setVisible(false);
        } else {
            lblErrorCedula.setText("El número de cédula no es valido");
            lblErrorCedula.setVisible(true);
        }
    }//GEN-LAST:event_txtIdClienteKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
        if (Validador.esNumeroCorrecto(txtTelefono.getText())) {
            lblErrorTelefono.setVisible(false);
        } else {
            lblErrorTelefono.setText("Numero de telefono incorrecto");
            lblErrorTelefono.setVisible(true);
        }
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
        
        if (Validador.esNumeroCorrecto(txtTelefono.getText())) {
            lblErrorTelefono.setVisible(false);
        } else {
            lblErrorTelefono.setText("Numero de telefono incorrecto");
            lblErrorTelefono.setVisible(true);
        }
    }//GEN-LAST:event_txtTelefonoActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblApellidoCliente;
    private javax.swing.JLabel lblDireccionCliente;
    private javax.swing.JLabel lblErrorApellido;
    private javax.swing.JLabel lblErrorCedula;
    private javax.swing.JLabel lblErrorDireccion;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JLabel lblErrorTelefono;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
