
import java.awt.BorderLayout;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author PC
 */
public class PnlAutos extends javax.swing.JPanel {
    DefaultTableModel dtmAutos;
    

    /**
     * Creates new form NewJPanel
     */
    public PnlAutos() {
        initComponents();
        dtmAutos = new DefaultTableModel();
        dtmAutos.addColumn("Marca");
        dtmAutos.addColumn("Color");
        dtmAutos.addColumn("Tipo");
        dtmAutos.addColumn("Precio");
        tblAutos.setModel(dtmAutos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutos = new javax.swing.JTable();
        cmbStock = new javax.swing.JComboBox<>();
        lblStock = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblIngresarNuevoAuto = new javax.swing.JLabel();
        lblMarcaAutoNuevo = new javax.swing.JLabel();
        txtMarcaAutoNuevo = new javax.swing.JTextField();
        lblColorAutoNuevo = new javax.swing.JLabel();
        txtColorAutoNuevo = new javax.swing.JTextField();
        lblTipoAutoNuevo = new javax.swing.JLabel();
        txtTipoAutoNuevo = new javax.swing.JTextField();
        lblPrecioAutoNuevo = new javax.swing.JLabel();
        txtPracioAutoNuevo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        tblAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAutos);

        cmbStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Color", "Marca", "Tipo" }));
        cmbStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStockActionPerformed(evt);
            }
        });

        lblStock.setText("Stock");

        lblMarca.setText("Marca");

        lblColor.setText("Color");

        lblTipo.setText("Tipo");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblIngresarNuevoAuto.setText("Ingresar nuevo auto");

        lblMarcaAutoNuevo.setText("Marca");

        lblColorAutoNuevo.setText("Color");

        lblTipoAutoNuevo.setText("Tipo");

        lblPrecioAutoNuevo.setText("Precio");

        btnGuardar.setText("Guardar");

        jButton1.setText("Confirmar Seleccion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarca)
                            .addComponent(lblColor)
                            .addComponent(lblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbStock, 0, 166, Short.MAX_VALUE)
                                .addComponent(txtMarca)
                                .addComponent(txtColor)
                                .addComponent(txtTipo))
                            .addComponent(btnBuscar))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMarcaAutoNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(txtMarcaAutoNuevo))
                            .addComponent(lblIngresarNuevoAuto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblColorAutoNuevo)
                                    .addComponent(lblTipoAutoNuevo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtColorAutoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(txtTipoAutoNuevo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPrecioAutoNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPracioAutoNuevo)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 8, Short.MAX_VALUE)
                                        .addComponent(btnGuardar)
                                        .addGap(37, 37, 37))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStock)
                    .addComponent(lblIngresarNuevoAuto))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColor)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarcaAutoNuevo)
                            .addComponent(txtMarcaAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColorAutoNuevo)
                            .addComponent(txtColorAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoAutoNuevo)
                            .addComponent(txtTipoAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecioAutoNuevo)
                            .addComponent(txtPracioAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStockActionPerformed
        // TODO add your handling code here:
        if (cmbStock.getSelectedItem().toString().equals("Color")) {
            lblColor.setVisible(true);
            lblMarca.setVisible(false);
            lblTipo.setVisible(false);
            txtColor.setEnabled(true);
            txtColor.setVisible(true);
            txtMarca.setEnabled(false);
            txtMarca.setVisible(false);
            txtTipo.setEnabled(false);
            txtTipo.setVisible(false);
            btnBuscar.setVisible(true);
        } else {
            if (cmbStock.getSelectedItem().toString().equals("Marca")) {
                lblColor.setVisible(false);
                lblMarca.setVisible(true);
                lblTipo.setVisible(false);
                txtColor.setEnabled(false);
                txtColor.setVisible(false);
                txtMarca.setEnabled(true);
                txtMarca.setVisible(true);
                txtTipo.setEnabled(false);
                txtTipo.setVisible(false);
                btnBuscar.setVisible(true);
            }else{
                if (cmbStock.getSelectedItem().toString().equals("Tipo")) {
                    lblColor.setVisible(false);
                    lblMarca.setVisible(false);
                    lblTipo.setVisible(true);
                    txtColor.setEnabled(false);
                    txtColor.setVisible(false);
                    txtMarca.setEnabled(false);
                    txtMarca.setVisible(false);
                    txtTipo.setEnabled(true);
                    txtTipo.setVisible(true);
                    btnBuscar.setVisible(true);
                }
            }

        }
    }//GEN-LAST:event_cmbStockActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PnlConfirmacionDeCompra p1=new PnlConfirmacionDeCompra();
        p1.setSize(814, 550);
        p1.setLocation(0, 0);
        jPanel1.removeAll();
        jPanel1.add(p1,BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbStock;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColorAutoNuevo;
    private javax.swing.JLabel lblIngresarNuevoAuto;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarcaAutoNuevo;
    private javax.swing.JLabel lblPrecioAutoNuevo;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoAutoNuevo;
    private javax.swing.JTable tblAutos;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtColorAutoNuevo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMarcaAutoNuevo;
    private javax.swing.JTextField txtPracioAutoNuevo;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTipoAutoNuevo;
    // End of variables declaration//GEN-END:variables
}
